include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - prefer_single_quotes
    - public_member_api_docs
    - unnecessary_lambdas