name: nobitex
description: Dart wrapper for the Nobitex API
version: 0.0.1
homepage: https://github.com/nekofar/nobitex-api-dart-client
repository: https://github.com/nekofar/nobitex-api-dart-client
issue_tracker: https://github.com/nekofar/nobitex-api-dart-client/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dotenv: ^3.0.0
  lints: ^1.0.1
