name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0

      - uses: dart-lang/setup-dart@v1.2

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test --coverage=coverage
        env:
          NOBITEX_USERNAME: ${{ secrets.NOBITEX_USERNAME }}
          NOBITEX_PASSWORD: ${{ secrets.NOBITEX_PASSWORD }}

      - name: Collect test coverage
        run: dart run coverage:format_coverage --lcov --in=coverage --packages=.packages --out=coverage/lcov.info --report-on=lib

      - uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info

      - name: Setup pub credentials
        run: |
          mkdir -p ~/.pub-cache && cat <<EOF > ~/.pub-cache/credentials.json
          ${{ secrets.CREDENTIAL_JSON }}
          EOF

      - name: Publish the dart package
        run: dart pub publish -f
